### ISSUE TITLE
Route!

### ISSUE THREAD

**Issue by crysan** [lemmingzshadow/shiny_blog#1]
Hi!
`/blog`
not work
and
`/index.php/blog`
work
is page
> Sry. The requested page could not be found.

How to get rid `/index.php/` ?

**Comment by nekudo** [comment]
Hello.

You need to rewrite all requests to index.php in your webserver configuration.

In nginx you need to add a rewrite rule to your vhost like e.g.:
`location / {
    try_files $uri $uri/ /index.php?$args;
}`

In apache2 you can check: https://gist.github.com/RaVbaker/2254618

**Comment by crysan** [comment]
Yes!
Everything worked.
Thank you!
