### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by crysan** [lemmingzshadow/shiny_blog#2]
Hi!

I ask you to make comments on the blog .
That they were preserved, such as
`2016-01-23-hello-word.md` - is file blog
to
`2016-01-23-hello-word.cm` - is file comment

**Comment by nekudo** [comment]
Hello,

implementing the possibility to comment would add a lot of complexity to the software as such a feature requires validation, spam-protection, moderation (which requires some kind of adminpanel), ...
One of the main goals of this project is to keep the code simple and secure. This is why I won't implement such a feature.
Of course you are free to fork this project and create a more interactive version with a comment section.

**Comment by crysan** [comment]
Very sorry.
But I understand your position.
Thank you!
