### ISSUE TITLE
Help needed getting "shiny blog" running

### ISSUE THREAD

**Issue by phayz** [lemmingzshadow/shiny_blog#3]
I copied "shiny blog" to my shared hosting account and renamed the configuration file. Having done that, trying to access the blog resulted in 404 error message. I feel I must be missing a step somewhere.

**Comment by nekudo** [comment]
Make sure you vhost points to the correct path. There should be an index.php file in the root of your vhost.
Additionally you should configure your webserver to rewrite all requests to this index.php file.

**Comment by phayz** [comment]
Thank you. I have `shinyblog` working, though not entirely as I expected. I cloned the repo, navigated to the shinyblog directory, and ran "php -S localhost:8080". When I navigate to URL: localhost:8080/blog I see the list of blog posts and can view each by clicking on their title.
