### ISSUE TITLE
Are features such as images, code listings, and tag clouds available?

### ISSUE THREAD

**Issue by phayz** [lemmingzshadow/shiny_blog#4]
I am interesting in hosting my blog using shinyblog, but would like these additional features. Are they available, or are they able to be added?

**Comment by nekudo** [comment]
You can use images in markdown syntax or as html.
You highlight code using prism.js.
Examples can be found in this article from my blog:
https://nekudo.com/blog/composer-autoloading-performance
https://raw.githubusercontent.com/nekudo/nekudo.com/live/contents/articles/2015-10-15-composer-autoloading-performance.md

A tag cloud is not available.

**Comment by phayz** [comment]
Thank you! I really like the simplicity of shiny_blog.

I guess I could manually create a tag cloud, but I don't absolutely need it.
