### ISSUE TITLE
Trouble getting shiny_blog running

### ISSUE THREAD

**Issue by phayz** [lemmingzshadow/shiny_blog#9]
I have reinstalled shiny_blog to a new (share) web host, and can't get it working as I expect.

If I install it locally on my laptop (running Fedora 26), I can start the built-in PHP web server, access the URL, and shiny_blog is working as expected.

When I do the same for my blog - http://russelldickenson.id.au/shiny_blog/ - I get the message:

> Sry. The requested page could not be found.

What am I missing here? Any help is welcome.

**Comment by nekudo** [comment]
As you run the blog in a subfolder you need to adjust the routes in the config file.

**Comment by phayz** [comment]
Thank you. I have shiny blog installed in subfolder /shiny_blog. Does that mean I should edit the "routes" section of `config.php` and add the prefix "/shiny_blog"?

I feel that if I can get past this issue, shiny blog will be just the right blog system for me. However, I have zero experience with PHP, so perhaps shiny blog is not suited to me.
